export const LOAD_PODCAST_EPISODE = 'LOAD_PODCAST_EPISODE';
export const PLAY_EPISODE_DONE = 'PLAY_EPISODE_DONE';
export const ADD_PODCASTS = 'ADD_PODCASTS';
export const ADD_PLAY_LIST = 'ADD_PLAY_LIST';
export const REMOVE_PLAY_LIST = 'REMOVE_PLAY_LIST';
export const FLASH_MESSAGE = 'FLASH_MESSAGE';
export const REORDER_PLAY_LIST = 'REORDER_PLAY_LIST';
